#!/bin/bash
# Stage the published part of one architecture's bit database into a
# directory (a prjuray-db-<arch> repository checkout), without mkdb's working
# files (cache/, counts_*, unexplained_*, *.bak-*, evidence.json, ...).
#
#   generic/export_db.sh <arch> <outdir> <source commit>
#   generic/export_db.sh UltraScalePlus build/publish/prjuray-db-ultrascaleplus 1b36ac3
#
# Copies segbits_*.db, defaults_*.db, registers.{db,txt} and per die
# tilegrid.json + colmap.json, and writes README.md (provenance, dies and
# devices, per die check numbers from build/logs/check_<die>.log) and COPYING
# (CC0, as prjuray-db).  Existing database files in <outdir> are replaced;
# its .git is left alone.
set -eu
if [ $# -ne 3 ]; then
    echo "usage: $0 <arch> <outdir> <source commit>" >&2
    exit 2
fi
arch=$1
out=$2
commit=$3
top=$(cd "$(dirname "$0")/.." && pwd)
db=$top/build/db/$arch
[ -d "$db" ] || { echo "no database $db" >&2; exit 1; }
mkdir -p "$out"
find "$out" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

cp -p "$db"/segbits_*.db "$db"/defaults_*.db "$db"/registers.db "$db"/registers.txt "$out"/
dies=()
for d in "$db"/*/; do
    die=$(basename "$d")
    [ -f "$d/tilegrid.json" ] || continue
    dies+=("$die")
    mkdir -p "$out/$die"
    cp -p "$d/tilegrid.json" "$d/colmap.json" "$out/$die/"
done

cp "$top/generic/export/CC0-1.0.txt" "$out/COPYING"

built=$(find "$db" -maxdepth 1 -name 'segbits_*.db' -printf '%TY-%Tm-%Td %TH:%TM\n' | sort | tail -n 1)
python3 - "$arch" "$out" "$commit" "$built" "$top" "${dies[@]}" <<'EOF'
import json, os, re, statistics, sys
arch, out, commit, built, top = sys.argv[1:6]
dies = sys.argv[6:]
groups = json.load(open(os.path.join(top, 'build/meta/die_groups.json')))
devices = {}
for g in groups:
    names = sorted({d['device'] for d in g['devices']})
    for die in dies:
        if die in names:
            devices[die] = names
rows = []
for die in dies:
    p = os.path.join(top, 'build/logs', f'check_{die}.log')
    undoc, unowned = [], 0
    if os.path.exists(p):
        for line in open(p):
            m = re.search(r'unowned (\d+) undocumented \d+ bits (\d+)', line)
            if m:
                unowned += int(m.group(1))
                undoc.append(int(m.group(2)))
    med = int(statistics.median(undoc)) if undoc else '-'
    rows.append(f'| {die} | {", ".join(devices.get(die, [die]))} | '
                f'{len(undoc)} | {med} | {unowned} |')
nseg = len([f for f in os.listdir(out) if f.startswith('segbits_')])
readme = f"""# prjuray-db-{arch.lower()}: {arch} bit database

Bitstream documentation database for the AMD (Xilinx) {arch} dies available
in the **Vivado 2025.2 WebPACK** edition. It was generated by the
architecture independent `generic/` flow of
[Project U-Ray](https://github.com/mithro/prjuray) (source commit
`{commit}`, database built {built}).

This is a **work in progress** snapshot: the database does not yet explain
every set bit (see the table below). The repository only holds generated data;
issues, pull requests and the other GitHub features are turned off. Please
send reports and changes to the Project U-Ray repository.

## Contents

| File | Contents |
| ---- | -------- |
| `segbits_<tiletype>.db` ({nseg} files) | one line per feature: `<TILETYPE>.<feature> <bit> [<bit> ...]`. A bit is `<frame>_<bit>`: the frame within the tile and the bit within the tile's part of that frame. A `!` prefix marks a bit that must be clear |
| `defaults_<tiletype>.db` | bits that are set when a feature is *not* used |
| `registers.db`, `registers.txt` | configuration register settings (`BITSTREAM.*` properties) |
| `<die>/tilegrid.json` | per die: every tile with its type, grid position and bit ranges (frame base address, frame count, bit offset and bit count within the frames) |
| `<die>/colmap.json` | per die: grid column to frame column map |

Tile types found only at the bottom and top edge of a clock region row, which
have a different layout at each edge, split into two types: the top instances
get `<type>@TOP` (e.g. `RIOB18_SING@TOP`). An empty `segbits_*.db` file is a
tile type with no bits explained yet.

## Dies, devices and status

Devices that share a die share its tile grid and bit database. Each die is
checked against held-out designs that were not used to build the
database. A set bit is *undocumented* when no feature of the design
explains it, and *unowned* when no tile of the tile grid covers it.

| Die | Devices | Designs checked | Median distinct undocumented bits per design | Unowned bits (all designs) |
| --- | ------- | --------------- | -------------------------------------------- | -------------------------- |
""" + '\n'.join(rows) + """

## License

The database is released under CC0 1.0 Universal (see `COPYING`), like
[f4pga/prjuray-db](https://github.com/f4pga/prjuray-db).
"""
open(os.path.join(out, 'README.md'), 'w').write(readme)
EOF
echo "$arch: $(find "$out" -type f ! -path '*/.git/*' | wc -l) files, $(du -sh --exclude=.git "$out" | cut -f1)"
